services:
#  Angular Front-End Application --> run container from Dockerfile
  frontend:
    container_name: front-end
    build:
      context: angular-frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - microservice-network

#  MySQL database for the microservices
  database:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - database:/var/lib/mysql


#phpMyAdmin UI for MySQL Database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

#Volumes for the containers
volumes:
  database:

#Networks for the containers
networks:
  microservice-network:
    driver: bridge


