server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true


      routes:
        - id: owner
          uri: lb://OWNER
          predicates:
            - Path=/api/v1/owner/**
        - id: property
          uri: lb://PROPERTY
          predicates:
            - Path=/api/v1/property/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true