server:
  port: 9090
spring:
  application:
    name: owner
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/owner
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

keycloak:
  realm: spring-boot-angular
  auth-server-url: http://localhost:8080/auth
  resource: owner-service
  public-client: true
  bearer-only: true


